/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    AgentMaintenance: typeof import('./src/pages/AgentMaintenance.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    ArrayInput: typeof import('./src/components/ArrayInput.vue')['default']
    ArraySelect: typeof import('./src/components/ArraySelect.vue')['default']
    BApp: typeof import('bootstrap-vue-next')['BApp']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next')['BDropdownForm']
    BDropdownGroup: typeof import('bootstrap-vue-next')['BDropdownGroup']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next')['BDropdownItemButton']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    Compose: typeof import('./src/pages/Compose.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Console: typeof import('./src/pages/Console.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ContainerInspect: typeof import('./src/pages/ContainerInspect.vue')['default']
    ContainerLog: typeof import('./src/pages/ContainerLog.vue')['default']
    ContainerTerminal: typeof import('./src/pages/ContainerTerminal.vue')['default']
    Dashboard: typeof import('./src/pages/Dashboard.vue')['default']
    DashboardHome: typeof import('./src/pages/DashboardHome.vue')['default']
    DockerArtefact: typeof import('./src/components/DockerArtefact.vue')['default']
    DockerStats: typeof import('./src/components/DockerStats.vue')['default']
    EmptyLayout: typeof import('./src/layouts/EmptyLayout.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MobileStackList: typeof import('./src/pages/MobileStackList.vue')['default']
    NetworkInput: typeof import('./src/components/NetworkInput.vue')['default']
    NetworkInspectModal: typeof import('./src/components/NetworkInspectModal.vue')['default']
    ProgressTerminal: typeof import('./src/components/ProgressTerminal.vue')['default']
    ReleaseNotes: typeof import('./src/components/settings/ReleaseNotes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    Settings: typeof import('./src/pages/Settings.vue')['default']
    Setup: typeof import('./src/pages/Setup.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
    Uptime: typeof import('./src/components/Uptime.vue')['default']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
  }
}
